### ISSUE TITLE
Another update regarding the username update

### ISSUE THREAD

**Issue by mulliganaceous** [Aisuruneko/discordrollout#1]
Hullo @Aisuruneko,

Circa February 1, 2024, some users received a notification (I am not one of those) stating that they should update their username by March 3, 2024. Those who did not respond or continually refused would automatically be given a unique username. This is the first definitive evidence that the new usernames will apply to everyone.

I am proposing reviving this project to observe the rollouts of unique usernames to the remaining users who haven't updated their usernames.

Source: [Reddit](https://www.reddit.com/r/discordapp/comments/1agtd4s/discord_will_be_forcing_users_who_havent_updated/)

![finalhashling](https://github.com/Aisuruneko/discordrollout/assets/29824582/c086f26b-f2a1-430b-a16f-f8442355a137)

**Comment by Aisuruneko** [comment]
Hi!

So what I have been hearing is true - they are really rolling out the username force. Took them long enough.

Anyway, as far as this project goes, I don't know if there will be a need to bring it back from its archived state, but I can surely add onto it regarding the forced usernames. Unless, there is something I am misunderstanding.

In any case, thanks for providing this information!

**Comment by mulliganaceous** [comment]
> Hi!
> 
> So what I have been hearing is true - they are really rolling out the username force. Took them long enough.
> 
> Anyway, as far as this project goes, I don't know if there will be a need to bring it back from its archived state, but I can surely add onto it regarding the forced usernames. Unless, there is something I am misunderstanding.
> 
> In any case, thanks for providing this information!

As of now, I have not received this notice, nor are anyone that I know of. It is probably something that is proposed in an insider channel.

**Comment by mulliganaceous** [comment]
> Hi!
> 
> So what I have been hearing is true - they are really rolling out the username force. Took them long enough.
> 
> Anyway, as far as this project goes, I don't know if there will be a need to bring it back from its archived state, but I can surely add onto it regarding the forced usernames. Unless, there is something I am misunderstanding.
> 
> In any case, thanks for providing this information!

![Screenshot_20240212-154915.png](https://github.com/Aisuruneko/discordrollout/assets/29824582/9b3ed928-ea46-4499-b348-a277bdf63ff5)

**Update of 2024 Feb 12th** Discord's statement that they will assign unique usernames to the remaining users who have not updated their usernames are now official. Discord is also far more aggressive in pushing users to update their usernames, as the popup comes up _everytime you start_ your app. Moreover, on mobile, you need two clicks to decline updating your username.

Would you like to keep track on the progress of Discord assigning unique usernames to the remaining users?

**Comment by Aisuruneko** [comment]
Thanks for the extra info - not sure how I was not getting notified for this GH issue. We love GitHub.

Anyway, I am debating between firing back up the real-time data stuff or just updating the archive per new data. What do you think I should do @mulliganaceous?

**Comment by mulliganaceous** [comment]
I would prefer the real time data stuff. I suspect Discord will assign usernames both clientside and serverside. In this case:

Discord will assign a suggested username clientside for users starting up Discord on the 4th or later.

Discord will assign a random username serverside for the large amounts of inactive users still with numbertags.

**Comment by Aisuruneko** [comment]
Within the next few hours to tomorrow, I'll get it back up. Will close once I have done that, so if you have any other information you can leave it here or contact me on my Discord (thecodingguy)

Great, I pinged someone named thecodingguy on GitHub lol.

**Comment by mulliganaceous** [comment]
That is great to hear. Hopefully we can discuss more, and that I can contribute to tracking the unique names assignment process.

**Comment by Aisuruneko** [comment]
> That is great to hear. Hopefully we can discuss more, and that I can contribute to tracking the unique names assignment process.

One of my alts got an email. It looks like it will be server side changing. 
> This is a notice that if you do not update your username by **March 4, 2024**, Discord will assign a new, unique username to your account. We will try to assign you a unique username that is similar to your current username.

**Comment by mulliganaceous** [comment]
It is most likely a suggested username. I have "plugged" the first few choices, but now Discord is suggesting a lowercase variant of my name without the special characters, and a random four-digit sequence, something like "mulliganaceous2048".
