### ISSUE TITLE
Archive the website

### ISSUE THREAD

**Issue by mulliganaceous** [Aisuruneko/discordrollout#2]
It seems that the assignment phase ended in a fortnight where even deleted users are being applied to.

**Comment by Aisuruneko** [comment]
Yeah, I need to archive this. I just need more info, but I just should archive it in its current state, really.

**Comment by Aisuruneko** [comment]
This was done with commits [6523ff5](https://github.com/Aisuruneko/discordrollout/commit/6523ff5) (static) and [9d4ae76](https://github.com/Aisuruneko/discordrollout/commit/9d4ae76) (v3).
